apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-demo-ingress
spec:
  rules:
  - host: docker-demo-ingress.192.169.32.21.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName:  docker-demo-svc
          servicePort: 8080