apiVersion: v1
kind: Pod
metadata:
  name: simplepod3
spec:
  containers:
  - name: container3
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
