apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: etcd-snapshot
spec:
  containers:
  - image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    name: etcd-snapshot
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources: {}
    volumeMounts:
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
    - mountPath: /etcd-snapshot
      name: etcd-snapshot      
  hostNetwork: true
  volumes:
  - hostPath:
      path: /vagrant/generated-conf/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /vagrant/generated-conf/etcd-snapshot
      type: DirectoryOrCreate
    name: etcd-snapshot