apiVersion: v1
kind: Pod
metadata:
  name: simplepod2
spec:
  containers:
  - name: container2
    image: centos
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
